version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker-build.sh
      - run: GAMMA_CLI_PATH=./_bin/gamma-cli ./_bin/e2e.test

workflows:
  version: 2
  build:
    jobs:
      - build
