version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: ./git-submodule-checkout.sh
      - run: ./docker-build.sh
      - run: ./docker-test.sh
      - run: ./docker-push.sh

workflows:
  version: 2
  build:
    jobs:
      - build
